# Installations and imports

In [23]:
## when you pull this file from the repo make sure to pip install the following: pip install pandas, pip install ipykernel pip install matplotlib, pip install seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from bs4 import BeautifulSoup
import time

# 1. Luka's NBA data

In [9]:
luka_data_nba = pd.read_csv('data/luka_data.csv')
luka_data_nba.tail()

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
2,2020-21,21,DAL,NBA,PG,66,66,34.3,9.8,20.5,...,0.8,7.2,8.0,8.6,1.0,0.5,4.3,2.3,27.7,MVP-6ASNBA1
3,2021-22,22,DAL,NBA,PG,65,65,35.4,9.9,21.6,...,0.9,8.3,9.1,8.7,1.2,0.6,4.5,2.2,28.4,MVP-5ASNBA1
4,2022-23,23,DAL,NBA,PG,66,66,36.2,10.9,22.0,...,0.8,7.8,8.6,8.0,1.4,0.5,3.6,2.5,32.4,MVP-8CPOY-8ASNBA1
5,2023-24,24,DAL,NBA,PG,70,70,37.5,11.5,23.6,...,0.8,8.4,9.2,9.8,1.4,0.5,4.0,2.1,33.9,MVP-3CPOY-6ASNBA1
6,2024-25,25,DAL,NBA,PG,22,22,35.7,9.8,21.2,...,0.7,7.6,8.3,7.8,2.0,0.4,3.4,2.6,28.1,NaN

In [10]:
luke_advanced_data = pd.read_csv('data/luka_advanced.csv')
luke_advanced_data.tail()

,Season,Age,Team,Lg,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards
2,2020-21,21,DAL,NBA,PG,66,66,2262,25.3,0.587,...,36.0,5.1,2.6,7.7,0.163,6.1,0.7,6.8,5.1,MVP-6ASNBA1
3,2021-22,22,DAL,NBA,PG,65,65,2301,25.1,0.571,...,37.4,3.8,3.8,7.6,0.159,6.4,1.8,8.2,5.9,MVP-5ASNBA1
4,2022-23,23,DAL,NBA,PG,66,66,2391,28.7,0.609,...,37.6,7.3,2.9,10.2,0.204,7.6,1.4,8.9,6.6,MVP-8CPOY-8ASNBA1
5,2023-24,24,DAL,NBA,PG,70,70,2624,28.1,0.617,...,36.0,8.5,3.5,12.0,0.220,8.3,1.7,9.9,8.0,MVP-3CPOY-6ASNBA1
6,2024-25,25,DAL,NBA,PG,22,22,785,24.6,0.584,...,32.8,1.8,1.1,2.9,0.177,5.6,1.4,7.0,1.8,NaN

# 2. AD's NBA data

In [11]:
AD_data = pd.read_csv('data/AD.csv')
AD_data.tail()

,Season,Age,Team,Lg,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards
9,2021-22,28,LAL,NBA,C,40,40,1404,23.9,0.578,...,27.1,2.6,2.0,4.5,0.155,2.6,1.2,3.8,2.0,NaN
10,2022-23,29,LAL,NBA,C,56,54,1904,27.8,0.627,...,28.4,5.5,3.4,9.0,0.226,4.6,1.7,6.3,4.0,NaN
11,2023-24,30,LAL,NBA,C,76,76,2700,25.8,0.621,...,26.7,7.2,4.7,11.8,0.210,3.5,1.7,5.1,4.9,DPOY-4ASNBA2
12,2024-25,31,LAL,NBA,C,42,42,1440,27.4,0.601,...,30.4,3.8,2.4,6.2,0.208,4.5,1.2,5.8,2.8,NaN
13,13 Yrs,13 Yrs,13 Yrs,13 Yrs,NaN,778,771,26849,26.9,0.593,...,28.3,73.4,44.9,118.3,0.212,4.4,1.5,5.9,53.8,NaN

In [12]:
AD_advanced_data = pd.read_csv('data/AD_advanced.csv')
AD_advanced_data.tail()

,Season,Age,Team,Lg,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards
9,2021-22,28,LAL,NBA,C,40,40,1404,23.9,0.578,...,27.1,2.6,2.0,4.5,0.155,2.6,1.2,3.8,2.0,NaN
10,2022-23,29,LAL,NBA,C,56,54,1904,27.8,0.627,...,28.4,5.5,3.4,9.0,0.226,4.6,1.7,6.3,4.0,NaN
11,2023-24,30,LAL,NBA,C,76,76,2700,25.8,0.621,...,26.7,7.2,4.7,11.8,0.210,3.5,1.7,5.1,4.9,DPOY-4ASNBA2
12,2024-25,31,LAL,NBA,C,42,42,1440,27.3,0.601,...,30.4,3.8,2.4,6.2,0.208,4.5,1.2,5.8,2.8,NaN
13,13 Yrs,13 Yrs,13 Yrs,13 Yrs,NaN,778,771,26849,26.9,0.593,...,28.3,73.4,44.9,118.3,0.212,4.4,1.5,5.9,53.8,NaN

In [16]:
all_players = pd.read_csv('data/all_seasons.csv')
all_players.head(10)
##all_players.columns

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Randy Livingston,HOU,22.0,193.04,94.800728,Louisiana State,USA,1996,2,...,3.9,1.5,2.4,0.3,0.042,0.071,0.169,0.487,0.248,1996-97
1,1,Gaylon Nickerson,WAS,28.0,190.50,86.182480,Northwestern Oklahoma,USA,1994,2,...,3.8,1.3,0.3,8.9,0.030,0.111,0.174,0.497,0.043,1996-97
2,2,George Lynch,VAN,26.0,203.20,103.418976,North Carolina,USA,1993,1,...,8.3,6.4,1.9,-8.2,0.106,0.185,0.175,0.512,0.125,1996-97
3,3,George McCloud,LAL,30.0,203.20,102.058200,Florida State,USA,1989,1,...,10.2,2.8,1.7,-2.7,0.027,0.111,0.206,0.527,0.125,1996-97
4,4,George Zidek,DEN,23.0,213.36,119.748288,UCLA,USA,1995,1,...,2.8,1.7,0.3,-14.1,0.102,0.169,0.195,0.500,0.064,1996-97
5,5,Gerald Wilkins,ORL,33.0,198.12,102.058200,Tennessee-Chattanooga,USA,1985,2,...,10.6,2.2,2.2,-5.8,0.031,0.064,0.203,0.503,0.143,1996-97
6,6,Gheorghe Muresan,WAS,26.0,231.14,137.438376,NaN,USA,1993,2,...,10.6,6.6,0.4,6.9,0.098,0.217,0.185,0.618,0.024,1996-97
7,7,Glen Rice,CHH,30.0,203.20,99.790240,Michigan,USA,1989,1,...,26.8,4.0,2.0,3.2,0.025,0.087,0.272,0.605,0.088,1996-97
8,8,Glenn Robinson,MIL,24.0,200.66,106.594120,Purdue,USA,1994,1,...,21.1,6.3,3.1,-2.9,0.051,0.144,0.278,0.528,0.146,1996-97
9,9,Grant Hill,DET,24.0,203.20,102.058200,Duke,USA,1994,1,...,21.4,9.0,7.3,6.9,0.049,0.232,0.283,0.556,0.356,1996-97

In [15]:
AD_data.columns

Index(['Season', 'Age', 'Team', 'Lg', 'Pos', 'G', 'GS', 'MP', 'PER', 'TS%',
       '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%',
       'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP',
       'Awards'],
      dtype='object')

In [25]:
# Base URLs
index_url = "https://www.basketball-reference.com/players/"
base_player_url = "https://www.basketball-reference.com"

# Headers to mimic a real browser request
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

# Function to get player stats
def get_player_stats(player_link):
    try:
        response = requests.get(player_link, headers=headers)
        if response.status_code != 200:
            print(f"Skipping {player_link} (status code: {response.status_code})")
            return None
        
        soup = BeautifulSoup(response.text, "html.parser")

        # Get player name safely
        name_tag = soup.find("h1", itemprop="name")
        name = name_tag.text.strip() if name_tag else "Unknown"

        # Find the career totals row
        career_row = soup.find("tfoot").find("tr") if soup.find("tfoot") else None
        if not career_row:
            print(f"Skipping {name} (no career totals found)")
            return None
        
        # Extract key stats
        def get_stat(stat_name):
            stat_cell = career_row.find("td", {"data-stat": stat_name})
            return stat_cell.text.strip() if stat_cell else "N/A"

        pts = get_stat("pts")
        reb = get_stat("trb")
        ast = get_stat("ast")
        vorp = get_stat("vorp")
        per = get_stat("per")

        return [name, player_link, pts, reb, ast, vorp, per]

    except Exception as e:
        print(f"Error processing {player_link}: {e}")
        return None

# Get player links from index pages
player_links = []
for letter in "abcdefghijklmnopqrstuvwxyz":
    response = requests.get(index_url + letter + "/", headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")
    
    table = soup.find("table", {"id": "players"})
    if table:
        for row in table.find("tbody").find_all("tr"):
            cols = row.find_all("td")
            if cols:
                link_tag = cols[0].find("a")
                link = base_player_url + link_tag["href"] if link_tag else None
                if link:
                    player_links.append(link)
    
    time.sleep(1)  # Be polite and avoid getting blocked

# Scrape stats for each player
all_stats = []
for link in player_links:
    player_stats = get_player_stats(link)
    if player_stats is not None:
        all_stats.append(player_stats)
    
    time.sleep(1)  # Avoid rate-limiting

# Create DataFrame
players_stats_df = pd.DataFrame(all_stats, columns=["Name", "Link", "PTS", "REB", "AST", "VORP", "PER"])

# Save to CSV
players_stats_df.to_csv("all_nba_players_stats.csv", index=False)

print(players_stats_df.head())  # Preview the data

Empty DataFrame
Columns: [Name, Link, PTS, REB, AST, VORP, PER]
Index: []