# Installations and imports

In [23]:
## when you pull this file from the repo make sure to pip install the following: pip install pandas, pip install ipykernel pip install matplotlib, pip install seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Luka's NBA data

In [24]:
luka_data_nba = pd.read_csv('data/luka_data.csv')
luka_data_nba.tail()

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
2,2020-21,21,DAL,NBA,PG,66,66,34.3,9.8,20.5,...,0.8,7.2,8.0,8.6,1.0,0.5,4.3,2.3,27.7,MVP-6ASNBA1
3,2021-22,22,DAL,NBA,PG,65,65,35.4,9.9,21.6,...,0.9,8.3,9.1,8.7,1.2,0.6,4.5,2.2,28.4,MVP-5ASNBA1
4,2022-23,23,DAL,NBA,PG,66,66,36.2,10.9,22.0,...,0.8,7.8,8.6,8.0,1.4,0.5,3.6,2.5,32.4,MVP-8CPOY-8ASNBA1
5,2023-24,24,DAL,NBA,PG,70,70,37.5,11.5,23.6,...,0.8,8.4,9.2,9.8,1.4,0.5,4.0,2.1,33.9,MVP-3CPOY-6ASNBA1
6,2024-25,25,DAL,NBA,PG,22,22,35.7,9.8,21.2,...,0.7,7.6,8.3,7.8,2.0,0.4,3.4,2.6,28.1,NaN

In [25]:
luka_advanced_data = pd.read_csv('data/luka_advanced.csv')
luka_advanced_data.tail()

,Season,Age,Team,Lg,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards
2,2020-21,21,DAL,NBA,PG,66,66,2262,25.3,0.587,...,36.0,5.1,2.6,7.7,0.163,6.1,0.7,6.8,5.1,MVP-6ASNBA1
3,2021-22,22,DAL,NBA,PG,65,65,2301,25.1,0.571,...,37.4,3.8,3.8,7.6,0.159,6.4,1.8,8.2,5.9,MVP-5ASNBA1
4,2022-23,23,DAL,NBA,PG,66,66,2391,28.7,0.609,...,37.6,7.3,2.9,10.2,0.204,7.6,1.4,8.9,6.6,MVP-8CPOY-8ASNBA1
5,2023-24,24,DAL,NBA,PG,70,70,2624,28.1,0.617,...,36.0,8.5,3.5,12.0,0.220,8.3,1.7,9.9,8.0,MVP-3CPOY-6ASNBA1
6,2024-25,25,DAL,NBA,PG,22,22,785,24.6,0.584,...,32.8,1.8,1.1,2.9,0.177,5.6,1.4,7.0,1.8,NaN

# 2. AD's NBA data

In [26]:
AD_data = pd.read_csv('data/AD.csv')
AD_data.tail()

,Season,Age,Team,Lg,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards
9,2021-22,28,LAL,NBA,C,40,40,1404,23.9,0.578,...,27.1,2.6,2.0,4.5,0.155,2.6,1.2,3.8,2.0,NaN
10,2022-23,29,LAL,NBA,C,56,54,1904,27.8,0.627,...,28.4,5.5,3.4,9.0,0.226,4.6,1.7,6.3,4.0,NaN
11,2023-24,30,LAL,NBA,C,76,76,2700,25.8,0.621,...,26.7,7.2,4.7,11.8,0.210,3.5,1.7,5.1,4.9,DPOY-4ASNBA2
12,2024-25,31,LAL,NBA,C,42,42,1440,27.4,0.601,...,30.4,3.8,2.4,6.2,0.208,4.5,1.2,5.8,2.8,NaN
13,13 Yrs,13 Yrs,13 Yrs,13 Yrs,NaN,778,771,26849,26.9,0.593,...,28.3,73.4,44.9,118.3,0.212,4.4,1.5,5.9,53.8,NaN

In [27]:
AD_advanced_data = pd.read_csv('data/AD_advanced.csv')
AD_advanced_data.tail(5)

,Season,Age,Team,Lg,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards
9,2021-22,28,LAL,NBA,C,40,40,1404,23.9,0.578,...,27.1,2.6,2.0,4.5,0.155,2.6,1.2,3.8,2.0,NaN
10,2022-23,29,LAL,NBA,C,56,54,1904,27.8,0.627,...,28.4,5.5,3.4,9.0,0.226,4.6,1.7,6.3,4.0,NaN
11,2023-24,30,LAL,NBA,C,76,76,2700,25.8,0.621,...,26.7,7.2,4.7,11.8,0.210,3.5,1.7,5.1,4.9,DPOY-4ASNBA2
12,2024-25,31,LAL,NBA,C,42,42,1440,27.3,0.601,...,30.4,3.8,2.4,6.2,0.208,4.5,1.2,5.8,2.8,NaN
13,13 Yrs,13 Yrs,13 Yrs,13 Yrs,NaN,778,771,26849,26.9,0.593,...,28.3,73.4,44.9,118.3,0.212,4.4,1.5,5.9,53.8,NaN

In [31]:
AD_advanced_data = AD_data.head(len(AD_data) - 1)
AD_data = AD_data.head(len(AD_data) - 1)
AD_data.index += 1